debug: true
mode:  "dev"
templates.path: "%root_dir%/templates"
data_dir:  "%root_dir%/data"
cache_dir: "%data_dir%/cache"

# Login
login.enabled:     false
login.realm:       "Feedbox - Protected Area"
login.algorithm:   "plaintext"
login.credentials:
  #admin: "feedbox"

# Database (PDO)
database_adapter:  "sqlite"
database_dsn:      "%data_dir%/database.sdb"
database_username: ""
database_password: ""

# Feed runner
runner.timeout: 10
runner.default_worker: "Nogo\Feedbox\Feed\Worker\Rss"

# API
api.content_type: "application/json"
api.controller:
    - "Nogo\Feedbox\Controller\Sources"
    - "Nogo\Feedbox\Controller\Items"


