debug: true
mode:  "dev"
templates.path: "%root_dir%/templates"
data_dir:  "%root_dir%/data"
cache_dir: "%data_dir%/cache"

log.enabled: true
log_dir:     "%data_dir%/log"

# Login
login.enabled:     false
login.algorithm:   "plaintext"
login.expire:      "+2 weeks"
login.credentials:
  #admin: "feedbox"

# Database (PDO)
database_adapter:  "sqlite"
database_dsn:      "%data_dir%/database.sdb"
database_username: ""
database_password: ""

# Feed setting
fetcher.timeout: 10
worker.default: "Nogo\Feedbox\Feed\Rss"

# API
api.version:      "v1"
api.migration.ignore:
    - 1368823260
api.content_type: "application/json"
api.controller:
    - "Nogo\Feedbox\Controller\Access"
    - "Nogo\Feedbox\Controller\Items"
    - "Nogo\Feedbox\Controller\Settings"
    - "Nogo\Feedbox\Controller\Sources"
    - "Nogo\Feedbox\Controller\Tags"
    - "Nogo\Feedbox\Controller\Updates"

# Assets
asset:
    asset_dir: "%root_dir%/public/assets"
    css:
        files:
            - "%src_dir%/Nogo/Feedbox/Resources/css/bootstrap.min.css"
            - "%src_dir%/Nogo/Feedbox/Resources/css/font-awesome.min.css"
            - "%src_dir%/Nogo/Feedbox/Resources/css/style.css"
        out: "main.css"
        filter:
            - "Nogo\Filter\Merge"
    javascript:
        files:
            - "%src_dir%/Nogo/Feedbox/Resources/js/vendor/jquery.min.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/vendor/underscore.min.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/vendor/backbone.min.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/vendor/moment.min.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/vendor/bootstrap.min.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/app.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/module/helper.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/module/item.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/module/source.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/module/sidebar.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/module/content.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/module/routes.js"
            - "%src_dir%/Nogo/Feedbox/Resources/js/init.js"
        out: "scripts.js"
        filter:
            - "Nogo\Filter\Merge"