debug: true
mode:  "dev"
templates.path: "%root_dir%/templates"
data_dir:  "%root_dir%/data"
cache_dir: "%data_dir%/cache"

log.enabled: true
log_dir:     "%data_dir%/log"

# Login
login.enabled:     false
login.realm:       "Feedbox - Protected Area"
login.algorithm:   "plaintext"
login.credentials:
  #admin: "feedbox"

# Database (PDO)
database_adapter:  "sqlite"
database_dsn:      "%data_dir%/database.sdb"
database_username: ""
database_password: ""

# Feed setting
fetcher.timeout: 10
worker.default: "Nogo\Feedbox\Feed\Rss"

# API
api.version:      "v1"
api.migration.ignore:
    - 1368823260
api.content_type: "application/json"
api.controller:
    - "Nogo\Feedbox\Controller\Items"
    - "Nogo\Feedbox\Controller\Settings"
    - "Nogo\Feedbox\Controller\Sources"
    - "Nogo\Feedbox\Controller\Tags"
